export const FETCH_CARDS_START = 'FETCH_CARDS_START'
export const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS'
export const FETCH_CARDS_FAILURE = 'FETCH_CARDS_FAILURE'

export const ADDED_TO_BASKET = 'ADDED_TO_BASKET'
export const REMOVE_TO_BASKET = 'REMOVE_TO_BASKET'



